package main

import (
	"log"
	"net/http"
	"os"
	"path/filepath"

	"fourinrow/analytics"
	"fourinrow/db"
	"fourinrow/server"
)

// spaHandler serves the index.html for any unknown route to support React Router (SPA)
type spaHandler struct {
	staticPath string
	indexPath  string
}

func (h spaHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// join the static path with the requested URL path
	path := filepath.Join(h.staticPath, r.URL.Path)

	// Check if the file exists on disk
	_, err := os.Stat(path)

	// If the file does NOT exist (like /game, /leaderboard), serve index.html
	if os.IsNotExist(err) {
		http.ServeFile(w, r, filepath.Join(h.staticPath, h.indexPath))
		return
	} else if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// If the file DOES exist, serve it normally
	http.FileServer(http.Dir(h.staticPath)).ServeHTTP(w, r)
}

func main() {
	// 1. Initialize database
	db.InitDB()

	// 2. Initialize Analytics (Try Kafka, fallback to Stub)
	// We point to localhost:9092 because that is where Docker is running Kafka
	kafkaBrokers := []string{"localhost:9092"}
	analytics.Producer = analytics.NewKafkaProducer(kafkaBrokers, "game-events")
	
	if analytics.Producer == nil {
		analytics.Producer = analytics.NewStubProducer()
	}
    defer analytics.Producer.Close()

	http.HandleFunc("/ws", server.WebSocketHandler)
	http.HandleFunc("/leaderboard", server.LeaderboardHandler)

	// Serve the "dist" folder generated by 'npm run build'
	spa := spaHandler{staticPath: "./client/dist", indexPath: "index.html"}
	http.Handle("/", spa)

	log.Println("Server running on :5000")
	log.Fatal(http.ListenAndServe(":5000", nil))
}